### ISSUE TITLE
Type issues after extensions update

### ISSUE THREAD

**Issue by PerLycke** [modulovalue/dart_intersperse#3]
Hi. I got a lot of type errors after the latest update due to the extensions. If you define types as Iterable in the same dart file as you import intersperse you will get the following errors.

I know one solution is naming the intersperse import, but that creates a weird syntax when using it.

<img width="545" alt="Screenshot 2021-02-04 at 09 44 10" src="https://user-images.githubusercontent.com/8590720/106867147-8b84d800-66cd-11eb-8059-663e70d25c0e.png">

**Comment by modulovalue** [comment]
<img width="404" alt="Bildschirmfoto 2021-02-04 um 11 52 28" src="https://user-images.githubusercontent.com/24444584/106882797-787b0380-66df-11eb-8dc8-80800dbfebb6.png">

Sadly I could not reproduce this issue the way you described it.

But it looks very similar to an error that happens when one accidentally gives a variable the name of a builtin type such as bool or in this case Iterable.

<img width="458" alt="Bildschirmfoto 2021-02-04 um 11 45 13" src="https://user-images.githubusercontent.com/24444584/106881940-72d0ee00-66de-11eb-8457-5891e1a4c466.png">

I have to ask, even if that would most likely be obvious: do you have a global variable called Iterable somewhere? (maybe from accidentally creating one in this intersperse package while exploring the API)

**Comment by modulovalue** [comment]
@PerLycke have you found out what caused the issue?

**Comment by PerLycke** [comment]
I'll grab some code for you to reproduce the issue tomorrow. Thanks for getting back to me 👍

**Comment by PerLycke** [comment]
@modulovalue The simplest of test also reproduces the issue, see screenshot.

I'm using Flutter stable, 1.22.6

<img width="567" alt="Screenshot 2021-02-08 at 10 02 03" src="https://user-images.githubusercontent.com/8590720/107197925-d156de80-69f4-11eb-8976-ee5cc4205146.png">

**Comment by modulovalue** [comment]
Sadly, It doesn't give me an error when I try it.

What's weird in your screenshot is that the import is not grayed-out but It should be, because it's an import that isn't being used. 
You could try command+clicking on the import to remove stuff from the local copy of intersperse.
If the error goes away then you found the culprit, if not, then it might not be intersperses fault.

I don't know what else could be causing it, sorry.

**Comment by PerLycke** [comment]
Without doing anything in particular the issue is no longer there, so closing this.
